---
dist: bionic
language: ruby
addons:
  postgresql: "9.5"
services:
  - postgresql
  - redis-server
# We're trying to cache bundler gems
cache:
  directories:
    - vendor/bundle
    - /home/travis/.rvm/
    # Needed for speed up pyenv installation
    - /opt/pyenv
stages:
  - name: tests
    if: type = pull_request
  - name: deploy
    if: branch in (master) AND type != pull_request
before_install:
  - gem install bundler:1.16.1
install:
  - pip install ansible==2.9.6
jobs:
  include:
    - stage: tests
      name: "Test given pull-request"
      env:
        - RAILS_ENV=test
      script: |
        psql -c 'create database pay_cryptoprocessing_test;' -U postgres
        bundle install
        rails db:migrate
        bundle exec rspec
    - stage: deploy
      name: "Deploy code to target servers"
      env: LIMIT=azure_oomag_api_docs_master
      before_script: |
        echo "Checkout ansible controller repository"
        eval "$(ssh-agent -s)"
        ssh-add <(echo "$MACHINE_GUNNER_PKEY")
        export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git clone --depth=1 git@github.com:oomag/ansible_controller.git
        echo "Ensure roles needed for deploy"
        pushd ansible_controller
        ./tools/get-roles.sh docs
        echo "Ensure SSH key to login to target hosts"
        export ANSIBLE_VAULT_PASSWORD_FILE=$(readlink -f ./tools/get-vault-pass)
        ansible-playbook --limit $LIMIT --tags local -e @vars/extra.yaml run-ci-prerequisites.yml
        for key in /tmp/.ssh/*; do
          ssh-add $key
        done
      script: |
        echo "Run deploy on $LIMIT nodes set"
        ansible-playbook --limit $LIMIT -e @vars/extra.yaml run-docs.yml

